### ISSUE TITLE
Inventory creation bugged

### ISSUE THREAD

**Issue by Eylexander** [Eylexander/Project-1B#11]
Hey @dannyhpy, je me suis enfin lancé dans un semblant de "bot RPG" et j'ai donc réaliser un inventaire qui se développe, mais malheureusement j'ai remarqué que la création de celui-ci ne marche pas comme il le faudrait. J'ai constaté avoir besoin de forcer une nouvelle valeur à ajouter afin que celui-ci ne se créer.

Je t'invite à regarder dans : https://github.com/Eylexander/Project-1B/blob/main/commands/Economy/inventory.js
Pour peut-être voir là où je ne vois pas.
Merci d'avance !

**Comment by dannyhpy** [comment]
Tu n'utilises jamais ton `setstats` ?

**Comment by Eylexander** [comment]
En soit je voulais faire un petit system dans lequel je pourrai m'ajouter des "ressources" directement depuis ce fichier mais finalement je l'ai fait dans `work.js`

**Comment by dannyhpy** [comment]
Et bien dans le fichier `inventory.js`, vu que tu n'utilises pas ton `setstats`, si le compte n'existe pas, il n'est jamais créé

**Comment by Eylexander** [comment]
Effectivement, après avoir relu le tutoriel et ce que tu m'as dis, ça marche beaucoup mieux.
Merci !
