### ISSUE TITLE
Hosting uncomfortable

### ISSUE THREAD

**Issue by Eylexander** [Eylexander/Project-1B#12]
Hey @dannyhpy, comme tu le sais je m'étais acheté un Raspberry Pi afin de trouver une solution d'hébergement de mon Projet. Malheureusement, après des heures de recherches je n'ai pas trouvé de moyen simplifié pour accéder à mon appareil en dehors d'un simple localhost. Aurais-tu des solutions venant de ton expérience ?

**Comment by dannyhpy** [comment]
Utiliser `sshd` pour accéder à un _shell_ à distance.

```
# On l'active à la liste des services au démarrage
systemctl enable sshd.service

# On le démarre tout de suite
systemctl start sshd.service
```

Tu te connectes avec ton PC avec `ssh pi@<IP DU RASBPERRYPI>`

**Comment by Eylexander** [comment]
Je vois la manip, c'est déjà mieux que d'installer des dizaines d'applications tierces. Le problème restant pour moi l'ouverture de mes ports. Je trouve aucun moyen. J'ai beau littéralement détruite le pare feu et pourtant toujours rien.

**Comment by dannyhpy** [comment]
T'as pas à toucher au pare-feu si tu veux juste te connecter à ton Pi depuis le PC sous le même réseau.

**Comment by dannyhpy** [comment]
Après, si tu veux ouvrir tes ports, rends-toi sur les paramètres de ton routeur et rajoute une règle NAT

**Comment by Eylexander** [comment]
L'idée c'est vraiment de pouvoir accéder à mon Raspberry à distance, sans être sous le même réseau. Et c'est avec mon routeur que j'ai du mal puisque c'est lui qui bloque les connexions externes.
Malgré le fait que j'ai installé l'application Pm2 et que je peux y accéder par là (ce qui est étonnant).
Comment rajouter une règle NAT (Box => Livebox de chez Orange)

**Comment by dannyhpy** [comment]
> Malgré le fait que j'ai installé l'application Pm2 et que je peux y accéder par là (ce qui est étonnant).

Tu passes par **leur** serveur (_PM2_) en réalité, pas celui du Pi directement
<hr>

Je t'invite à regarder sur Internet pour ouvrir tes ports sur ta Livebox, je n'en ai aucune idée
Il me semblait qu'ils exposaient un site LAN pour y accéder http://livebox/ mais je peux me tromper

**Comment by Eylexander** [comment]
Et bien finalement je retourne au point de départ, ça s'annonce assez compliqué mais ce sera bien mieux après.
Merci quand même !
