### ISSUE TITLE
Simple JS problem

### ISSUE THREAD

**Issue by Eylexander** [Eylexander/Project-1B#16]
Salut @dannyhpy, ça fait bien longtemps que j'ai pas codé mais pour le fun j'ai essayé de m'attaquer aux messages privés mais malheuresement, c'est mon système de logs qui bloque tout, j'ai essayé en reproduisant quelque chose que je n'ai pas compris : 

```
${message.guild.name === null ? "DM" : message.guild.name}
```

Comment marche cette forme ? Merci d'avance

**Comment by dannyhpy** [comment]
Le bout de code ci-dessus sert simplement à récupérer le nom du serveur ou "DM" si c'est un message privé

```js
const name = message.guild.name === null ? "DM" : message.guild.name
// 'name' sera soit le nom du serveur (par ex.: "Eylexander's Server"), soit "DM"
```

**Comment by Eylexander** [comment]
Après plusieurs essais, je ne vois pas comment implémenter cette fonction sous forme de variable puisqu'il est surtout compris dans mon système de logs :

```
var stream = fs.createWriteStream(`${folder}/${file}.txt`, {'flags': 'w'});

exports.onMessage = function (client, message) {
  stream.write(`[${moment().format('YYYY-MM-DD HH:mm:ss.SSS')}] ${message.author.username} (${message.author.id}) : "${message.content}" on [${message.channel.name === null ? "DM" : message.channel.name} (${message.channel.id === null ? "DM" : message.channel.id}) : ${message.guild.name === null ? "DM" : message.guild.name} (${message.guild.id === null ? "DM" : message.guild.id})] \r\n`);
}
```

Donc en gros, ça ressemble à ça mon bout de code, mais en fait ça le fait quand même crash quand je lui envoie un mp, je me doute que crée une variable pourrait aider

L'erreur qui survient est au niveau du `message.guild.name`, puisqu'il considère qu'il n'y a pas de guild

**Comment by Eylexander** [comment]
Finalement j'ai exploré l'idée de ne pas utiliser `message.guild.name` mais juste `message.guild` pour juste détecter s'il y aune guild et donc j'ai refait mes lignes et mes "conditions" du bout de code, je ressort avec un code qui marche super bien : 

```
stream.write(`[${moment().format('YYYY-MM-DD HH:mm:ss.SSS')}] ${message.author.username} (${message.author.id}) : "${message.content}" ${message.guild === null ? "in DM" : "on [#" + message.channel.name + "("+message.channel.id+") : " + message.guild.name + " ("+message.guild.id+")]"} \r\n`);
```

Ce qui donne bien ce que je veux : 

```
[2022-07-29 16:58:16.652] Eylexander (344526513577918477) : "hi" in DM  
```

**Comment by dannyhpy** [comment]
> Le bout de code ci-dessus sert simplement à récupérer le nom du serveur ou "DM" si c'est un message privé
> 
> ```js
> const name = message.guild.name === null ? "DM" : message.guild.name
> // 'name' sera soit le nom du serveur (par ex.: "Eylexander's Server"), soit "DM"
> ```

Oui, c'est moi qui m'était trompé en fait ^
```diff
- const name = message.guild.name === null ? "DM" : message.guild.name
+ const name = message.guild?.name ?? "DM"
```

**Comment by Eylexander** [comment]
Alors là j'ai jamais vu cette forme d'écriture, il y a de la doc qui explique ça quelque part ou c'est vraiment quelque chose de très peu utilisé ?

**Comment by dannyhpy** [comment]
### ?.
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining
<hr>

### ??
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Nullish_coalescing_operator
