### ISSUE TITLE
Logs Problem

### ISSUE THREAD

**Issue by Eylexander** [Eylexander/Project-1B#2]
Hey @dannyhpy, je rencontre quelques problèmes avec mon log_boot, il marche parfaitement dans mon index, mais ne marche pas dans son fichier malgré qu'il ait ce qu'il lui faut. J'ai bien du mal à comprendre pourquoi.

**Comment by dannyhpy** [comment]
Comment ça ?

**Comment by Eylexander** [comment]
J'ai donc bien mon fichier log_boot.js dans le dossier Logs, qui charge dans un fichier logs.txt des informations bien précises. Le début du fichier exécute une inscription de la date au début du fichier et la suivante marque des evenements précis à chaque message reçu par le bot. Mais cette parti ne marche que dans l'index.js
Je me doute donc que l'expression "client.on" ne marche donc que dans l'index, mais je ne trouve pas d'alternative.

**Comment by dannyhpy** [comment]
Exoprte l'événement 'message' et importe là dans l'index

par exemple

**log_boot.js**
```js
exports.onMessage = function (client, message) { ... }
```

**index.js**
```js
const { onMessage } = require('./log_boot.js')
client.on('message', onMessage.bind(null, client))
```

**Comment by Eylexander** [comment]
Et bien je ne connaissait pas du tout cette fonction, mais elle marche parfaitement bien.

Merci !!
