### ISSUE TITLE
Simple JS problem

### ISSUE THREAD

**Issue by Eylexander** [Eylexander/Project-1B#3]
Hey @dannyhpy, ces derniers temps j'essaie d'avancer avec un meilleur rythme mais j'arrive pas à trouver de solution à mon "problème". J'aimerai rendre mon code un peu mieux et optimisé, en soit raccourcir mes conditions if.
Par exemple : pour un argument donné, ma commande info.js renvoie un certain script, mais je n'ai pas trouvé de moyen de créer des "aliases" dans des conditions if.
Si jamais tu aurais la réponse à mon problème cela m'aiderai pas mal !

**Comment by dannyhpy** [comment]
Un **OU**, c'est ce que tu cherches ?
```js
if (name === "photographier" || name === "photo") {
  photographyCommand.callback()
}
```

Pour plusieurs alias,
```js
// photographyCommand.aliases = ["photo", "foto", "photograph"]
 if (name === "photographier" || photographyCommand.aliases.includes(name)) {
  photographyCommand.callback()
}

**Comment by dannyhpy** [comment]
Si tu sais me donner un exemple, ça serait plus simple :+1:

**Comment by Eylexander** [comment]
Le "problème" s'applique vraiment à mon info.js parce qu'il est sous cette forme et j'aimerais savoir s'il est possible de la raccourcir :

```
if (args[0] === 'server' || args[0] === 'serveur' || args[0] === 'serv') {
...
}
````

**Comment by dannyhpy** [comment]
Dans ce cas,
```js
if (['server', 'serveur', 'serv'].includes(args[0])) { ... }
```
ceci ?

**Comment by Eylexander** [comment]
> Dans ce cas,
> 
> ```js
> if (['server', 'serveur', 'serv'].includes(args[0])) { ... }
> ```
> 
> ceci ?

Ca marche parfaitement, merci !
