### ISSUE TITLE
Mention issue

### ISSUE THREAD

**Issue by Eylexander** [Eylexander/Project-1B#4]
Salut @dannyhpy, en regardant plus attentivement à mon index.js, j'ai remarqué une fonction qui ne marchait plus, celle-ci ayant pour but de répondre le prefix du bot en le mentionnant. Le code actuelle étant : 
```
if (message.content.slice().trim().split(/ +/)[0] == message.mentions.has(client.user.id)) {
    message.channel.send(`My prefix is \`\`${prefix}\`\``)
};
```

Le problème étant qu'en vérifiant via la console les valeurs de chaque partie, le code devrait marcher, mais ce n'est pas le cas.

**Comment by dannyhpy** [comment]
Si t'as vraiment envie d'être super précis, tu peux utiliser un _regex_, c'est pas simple à maîtriser cependant
```js
client.on('message', async function (message) {
  const mentionRegEx = new RegExp(`^<!?@${client.user.id}>$`)

  if (message.content.match(mentionRegEx)) {
    await message.channel.send('Mon préfixe est [...]')
  }
})
```
Là, il vérifie que si le message contient **uniquement** la mention pour continuer

Sinon, tu peux utiliser aller sur quelque chose de plus basique qui marche presque à tous les coups :
```js
if (message.content === `<@!${client.user.id}>`) {
  ...
}
```

**Comment by Eylexander** [comment]
La solution la plus simple marche le mieux, je pense avoir trop complexifié mon code quand j'ai voulu le faire et ça marchait plus.
Mais ducoup maintenant ça marche parfaitement, Merci !
