### ISSUE TITLE
Thinking about adding new Feature 

### ISSUE THREAD

**Issue by Eylexander** [Eylexander/Project-1B#6]
Hey @dannyhpy ! J'aimerais bien ajouter un système sur mon bot qui permet de lire des messages en particuliers avec lesquels il répond, par exemple :
`Salut !` répond `Bonjour !`
Le problème étant que presque tout les tutoriels conditionne le bot à ne lire que des commandes.
Je pourrais toujours ajouter cette fonction simplement dans l'`index.js` avec `client.on('message', message => { . . . })` mais dans l'idée j'aimerais bien pouvoir ranger ça dans des fichier et garder le plus épuré possible mon `index.js`

**Comment by dannyhpy** [comment]
Tu peux recopier le système que pour les commandes à quelques différences prêt.

Puis tu peux vérifier si la partie que tu cherches existe dans la commande, par exemple :
```js
var triggers = ["Salut !", "Ça va ?"]
// ...
client.on('message', (message) => {
  for (const trigger of triggers) {
    if (message.content.includes(trigger)) {
      // ...
      break
    }
  }
})
```

C'est pas un exemple très complet mais j'espère que ça te donnera une piste

**Comment by Eylexander** [comment]
Je viens d'appliquer ça pour ma vieille idée de système de mots bannis, ça marche parfaitement bien !
Merci !
