### ISSUE TITLE
File searching problem

### ISSUE THREAD

**Issue by Eylexander** [Eylexander/Project-1B#7]
Hey @dannyhpy ! j'ai récemment refait mon système de commande mais j'avais pour habitude d'utiliser des raccourcis pour rechercher mes variables pour rendre mon code universel.
Par exemple : `const var = require('./settings.json')`
Le problème ici étant que j'ai du mal à naviguer entre les fichiers en revenant à plus de 2 dossiers avec `require('../settings.json')`

En te remerciant pour ton aide une fois de plus !

**Comment by dannyhpy** [comment]
```js
const settings = require('../../settings.json')
```
Pour remonter dans un dossier parent, tu rajoutes `../`

**Comment by Eylexander** [comment]
Ca marche parfaitement bien, merci !
