### ISSUE TITLE
Random function little bit slow

### ISSUE THREAD

**Issue by Eylexander** [Eylexander/Project-1B#8]
Hey @dannyhpy, j'ai trouvé une fonction qui permet de renvoyer une variable aléatoire venant d'une liste, ce qui est pratique, mais j'ai réalisé que cette fonction était assez lente puisque lors d'un spam la réponse était toujours la même pendant 2 à 3 secondes. Ce qui niveau probabilité n'est que très peu plausible.
Code en question (exemple) : `response[Math.floor(Math.random()*response.length)]`
Connaitrais-tu un moyen d'optimiser cela ?

**Comment by dannyhpy** [comment]
T'es sûr ça fait ça à chaque fois ? Pourtant le bout de code que tu donnes est correct :thinking:

**Comment by Eylexander** [comment]
Et bien pour le coup pas tant que ça finalement, j'ai surement dû avoir énormément de chance puisque j'étais allé à des probas en dessous de 1%
