### ISSUE TITLE
Multiple variables condition is too specific

### ISSUE THREAD

**Issue by Eylexander** [Eylexander/Project-1B#9]
Hey @dannyhpy, un problème si petit que ça m'embête un peu de demander. En fait, j'ai une fonction assez stupide qui répond des mots au pif en fonction de mots au pif (Tu m'avais aidé là-dessus), mais je n'ai pas trouvé de moyen de rendre ces mots insensible aux majuscules.
Le code en question : `if (message.content.includes(trigger)) { . . . }`
Je n'ai pas trouvé de moyen d'y rajouter la fonction `.toLowerCase()` puisque celle-ci provoque un crash indiquant que cette fonction n'existe pas.

**Comment by dannyhpy** [comment]
Comme ça peut-être ?
```js
if (message.content.toLowerCase().includes(trigger)) {
  ...
}
```
Les `trigger`  de ta liste devront être en miniscule aussi

**Comment by Eylexander** [comment]
Et bien ça marche à la perfection.
Merci infiniment !
